import React, { useState } from 'react';
import { FileText, Download, Share2, Printer, CheckCircle, ShieldCheck, Lock, Activity, ChevronDown, FileJson, FileCode, FileDown } from 'lucide-react';

const API_BASE = '/api';

const ReportViewer = ({ master }) => {
  if (!master) return null;

  const [showFormatMenu, setShowFormatMenu] = useState(false);
  const [downloading, setDownloading] = useState(null);

  const caseId      = master?.case?.case_id || 'CASE-2026';
  const execSummary = master?.executive_summary || {};
  const decision    = master?.decision_intelligence || {};
  const validation  = master?.cross_notebook_validation || {};
  const audit       = master?.audit || {};
  const hasReport   = Boolean(master?.final_report);

  // Utility: trigger real browser download by navigating to the URL
  const triggerDownload = (url, label) => {
    setDownloading(label);
    setShowFormatMenu(false);
    // Use an anchor to force download
    const a = document.createElement('a');
    a.href = url;
    a.setAttribute('download', '');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => setDownloading(null), 2000);
  };

  const formats = [
    {
      id: 'html',
      label: 'Download HTML Report',
      desc: 'Styled, printable web report',
      icon: <FileCode size={15} />,
      url: `${API_BASE}/case/${encodeURIComponent(caseId)}/download/html`,
      accent: '#0284C7',
    },
    {
      id: 'pdf',
      label: 'Download PDF / TXT Report',
      desc: 'Official ReportLab PDF or plain-text fallback',
      icon: <FileDown size={15} />,
      url: `${API_BASE}/case/${encodeURIComponent(caseId)}/report`,
      accent: '#DC2626',
    },
    {
      id: 'json',
      label: 'Download JSON Package',
      desc: 'Full master intelligence package (JSON)',
      icon: <FileJson size={15} />,
      url: `${API_BASE}/case/${encodeURIComponent(caseId)}/download/json`,
      accent: '#7C3AED',
    },
  ];

  const handlePrint = () => window.print();

  const handleShare = () => {
    const url = `${window.location.origin}${API_BASE}/case/${encodeURIComponent(caseId)}/download/html`;
    if (navigator.clipboard) {
      navigator.clipboard.writeText(url).then(() => alert('HTML report link copied to clipboard!'));
    } else {
      alert(`Report link: ${url}`);
    }
  };

  return (
    <div className="card animate-fade-in">
      {/* ─── Header ─── */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="card-icon"><FileText size={24} color="var(--primary)" /></div>
          <div>
            <h3 style={{ margin: 0 }}>Final Public Safety Intelligence Package Report</h3>
            <p className="text-sm text-muted" style={{ margin: 0 }}>
              Generated by Master Orchestrator (Notebook 8) | Case Ref: {caseId}
            </p>
          </div>
        </div>

        <div className="flex gap-2" style={{ alignItems: 'center' }}>
          {/* Share */}
          <button
            type="button"
            className="btn btn-outline flex items-center gap-2"
            style={{ padding: '0.5rem 1rem' }}
            onClick={handleShare}
          >
            <Share2 size={16} /> Share
          </button>

          {/* Print */}
          <button
            type="button"
            className="btn btn-outline flex items-center gap-2"
            style={{ padding: '0.5rem 1rem' }}
            onClick={handlePrint}
          >
            <Printer size={16} /> Print
          </button>

          {/* Download dropdown */}
          <div style={{ position: 'relative' }}>
            <button
              type="button"
              className="btn btn-primary flex items-center gap-2"
              style={{ padding: '0.5rem 1.1rem', borderRadius: '8px 0 0 8px', borderRight: '1px solid rgba(255,255,255,0.25)' }}
              onClick={() => triggerDownload(formats[0].url, formats[0].label)}
              disabled={!!downloading}
            >
              <Download size={16} />
              {downloading ? 'Downloading…' : 'Download Report'}
            </button>
            <button
              type="button"
              className="btn btn-primary flex items-center"
              style={{ padding: '0.5rem 0.65rem', borderRadius: '0 8px 8px 0' }}
              onClick={() => setShowFormatMenu(v => !v)}
            >
              <ChevronDown size={15} />
            </button>

            {showFormatMenu && (
              <>
                {/* Backdrop to close on outside click */}
                <div
                  style={{ position: 'fixed', inset: 0, zIndex: 40 }}
                  onClick={() => setShowFormatMenu(false)}
                />
                <div style={{
                  position: 'absolute', right: 0, top: 'calc(100% + 8px)', zIndex: 50,
                  background: '#fff', border: '1px solid #E2E8F0', borderRadius: '12px',
                  boxShadow: '0 16px 40px -4px rgba(15,23,42,0.18)', minWidth: '280px', overflow: 'hidden',
                }}>
                  <div style={{ padding: '10px 14px 6px', fontSize: '10px', fontWeight: 700, color: '#94A3B8', textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                    Choose Format
                  </div>
                  {formats.map(f => (
                    <button
                      key={f.id}
                      type="button"
                      onClick={() => triggerDownload(f.url, f.label)}
                      style={{
                        display: 'flex', alignItems: 'flex-start', gap: '12px',
                        width: '100%', padding: '11px 16px', background: 'none', border: 'none',
                        cursor: 'pointer', textAlign: 'left',
                        borderTop: '1px solid #F1F5F9',
                        transition: 'background 0.15s',
                      }}
                      onMouseEnter={e => e.currentTarget.style.background = '#F8FAFC'}
                      onMouseLeave={e => e.currentTarget.style.background = 'none'}
                    >
                      <span style={{
                        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                        width: 30, height: 30, borderRadius: 8, flexShrink: 0,
                        background: f.accent + '18', color: f.accent,
                      }}>
                        {f.icon}
                      </span>
                      <span>
                        <span style={{ display: 'block', fontWeight: 700, fontSize: '13px', color: '#0F172A' }}>{f.label}</span>
                        <span style={{ display: 'block', fontSize: '11px', color: '#64748B', marginTop: 2 }}>{f.desc}</span>
                      </span>
                    </button>
                  ))}
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* ─── Report Body ─── */}
      <div style={{ backgroundColor: '#F8FAFC', padding: '1.5rem', borderRadius: 'var(--radius)', border: '1px solid #E2E8F0', maxHeight: '640px', overflowY: 'auto' }}>
        <div style={{ backgroundColor: 'white', padding: '2.5rem', boxShadow: 'var(--shadow-sm)', minHeight: '100%' }}>

          {/* Document Header */}
          <div className="text-center mb-6 border-b pb-6">
            <div className="flex justify-center items-center gap-2 mb-2 text-primary font-bold text-sm uppercase tracking-wider">
              <ShieldCheck size={20} /> Digital Public Safety Platform (ET AI Hackathon 2026)
            </div>
            <h2 className="mb-1 uppercase tracking-wide" style={{ color: 'var(--primary)', fontSize: '1.5rem' }}>
              Master Intelligence Package Report
            </h2>
            <p className="text-muted text-xs font-mono">
              Generated by digital_public_safety_platform.py (Notebook 8, Rev 4) | Ref: {caseId}<br/>
              SHA-256: <code>{audit.case_id_hash?.slice(0, 32) || '—'}</code>
            </p>
          </div>

          {/* Platform Dashboard Text */}
          {master.platform_dashboard_text && (
            <div className="mb-6">
              <h3 className="mb-2 text-primary border-b pb-1">0. Platform Dashboard (Real-Time)</h3>
              <pre style={{ background:'#0F172A', color:'#7DD3FC', padding:'1rem', borderRadius:'0.5rem', fontSize:'0.78rem', lineHeight:'1.6', overflowX:'auto', whiteSpace:'pre-wrap' }}>
                {master.platform_dashboard_text}
              </pre>
            </div>
          )}

          {/* Executive Summary */}
          <div className="mb-6">
            <h3 className="mb-2 text-primary border-b pb-1">1. Executive Summary</h3>
            <div className="p-3 rounded text-sm grid md:grid-cols-2 gap-1" style={{ backgroundColor: '#F1F5F9' }}>
              {Object.entries(execSummary).map(([key, val], idx) => (
                <p key={idx} style={{ margin: '0.1rem 0', fontSize: '0.82rem' }}>
                  <strong>{key}:</strong> {JSON.stringify(val)}
                </p>
              ))}
            </div>
          </div>

          {/* Official Incident Report */}
          {decision.incident_report && (
            <div className="mb-6">
              <h3 className="mb-2 text-primary border-b pb-1">2. Official Incident Report (Notebook 3 - Decision Intelligence)</h3>
              <pre style={{ background:'#F8FAFC', color:'#334155', padding:'1rem', borderRadius:'0.5rem', fontSize:'0.82rem', lineHeight:'1.6', whiteSpace:'pre-wrap', border:'1px solid #E2E8F0' }}>
                {decision.incident_report}
              </pre>
            </div>
          )}

          {/* Stakeholder Directives */}
          <div className="mb-6">
            <h3 className="mb-2 text-primary border-b pb-1">3. Stakeholder Action Directives (All Audiences)</h3>
            <div className="flex flex-col gap-3 text-sm">
              {[['Police Actions', decision.police_actions, '#1E40AF'],
                ['Bank Actions', decision.bank_actions, '#065F46'],
                ['Telecom Actions', decision.telecom_actions, '#6D28D9'],
                ['Citizen Actions', decision.citizen_actions, '#B45309']].map(([label, actions, color]) => (
                  actions?.length > 0 && (
                    <div key={label}>
                      <strong style={{color}}>{label}:</strong>
                      <ul style={{ paddingLeft: '1.2rem', margin: '0.25rem 0' }}>
                        {actions.map((a, i) => <li key={i}>{a}</li>)}
                      </ul>
                    </div>
                  )
              ))}
              {!decision.police_actions?.length && !decision.bank_actions?.length && (
                <div className="flex flex-col gap-2">
                  <div>
                    <strong>Citizen Advisory:</strong>
                    <ul style={{ paddingLeft: '1.2rem', margin: '0.25rem 0' }}>
                      {(decision.citizen_actions || ['Do not send any funds.', 'Report at cybercrime.gov.in']).map((a, i) => <li key={i}>{a}</li>)}
                    </ul>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Explainability Chain */}
          <div className="mb-6">
            <h3 className="mb-2 text-primary border-b pb-1">4. Explainability Chain (Why this decision was made)</h3>
            <ul style={{ paddingLeft: '1.2rem', margin: 0, fontSize: '0.85rem' }}>
              {(master.explainability || []).map((item, i) => (
                <li key={i} style={{ marginBottom: '0.25rem' }}>
                  <strong>{item.step}:</strong> {item.detail}
                </li>
              ))}
            </ul>
          </div>

          {/* Cross-Notebook Validation */}
          <div className="mb-6">
            <h3 className="mb-2 text-primary border-b pb-1">5. Cross-Notebook Validation (Consistency Check)</h3>
            <div className={`p-3 rounded text-xs border ${validation.is_consistent ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}>
              <p className={`font-bold mb-1 ${validation.is_consistent ? 'text-green-800' : 'text-red-800'}`}>
                {validation.is_consistent ? '✓ All engines consistent — no conflicts' : '⚠ Conflicts detected'}
              </p>
              {validation.conflicts_found?.length > 0 && (
                <ul style={{paddingLeft:'1rem',margin:0}}>
                  {validation.conflicts_found.map((c,i) => <li key={i}>{c}</li>)}
                </ul>
              )}
              <p className="text-muted mt-1">Force Human Review: {String(validation.force_human_review)}</p>
            </div>
          </div>

          {/* Risk Reduction Simulation */}
          {decision.risk_reduction_simulation?.length > 0 && (
            <div className="mb-6">
              <h3 className="mb-2 text-primary border-b pb-1">6. Risk Reduction Simulation (What actions reduce risk)</h3>
              <table style={{width:'100%',borderCollapse:'collapse',fontSize:'0.82rem'}}>
                <thead>
                  <tr style={{borderBottom:'2px solid #E2E8F0',background:'#F8FAFC',textAlign:'left'}}>
                    <th style={{padding:'0.4rem'}}>Action</th>
                    <th style={{padding:'0.4rem'}}>Risk Before</th>
                    <th style={{padding:'0.4rem'}}>Risk After</th>
                    <th style={{padding:'0.4rem'}}>Δ</th>
                  </tr>
                </thead>
                <tbody>
                  {decision.risk_reduction_simulation.map((sim, i) => (
                    <tr key={i} style={{borderBottom:'1px solid #F1F5F9'}}>
                      <td style={{padding:'0.4rem',fontSize:'0.78rem'}}>{sim.action}</td>
                      <td style={{padding:'0.4rem',fontWeight:'bold',color:'var(--critical)'}}>{sim.risk_before}</td>
                      <td style={{padding:'0.4rem',fontWeight:'bold',color:'var(--success)'}}>{sim.risk_after}</td>
                      <td style={{padding:'0.4rem',fontWeight:'bold',color:sim.risk_before > sim.risk_after ? 'var(--success)' : '#94A3B8'}}>-{sim.risk_before - sim.risk_after}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Legal Admissibility */}
          <div className="p-3 rounded border border-gray-300 bg-gray-50 text-xs">
            <div className="flex items-center gap-2 mb-1">
              <Lock size={14} color="var(--primary)"/>
              <span className="font-bold text-gray-800">Legal Admissibility &amp; Chain of Custody (Section 65B Indian Evidence Act)</span>
            </div>
            <p className="text-gray-600" style={{ margin: 0 }}>
              This document is cryptographically hashed and produced by an automated digital evidence pipeline.<br/>
              SHA-256 Digest: <code>{audit.case_id_hash || '—'}</code><br/>
              Report Status: <strong>{hasReport ? 'Generated ✓ — use Download Report above' : 'On-demand generation available via Download Report'}</strong>
            </p>
          </div>

          <div className="text-center mt-8 pt-4 border-t text-xs text-muted">
            <p style={{ margin: 0 }}>CONFIDENTIAL LAW ENFORCEMENT &amp; PUBLIC SAFETY DOCUMENT — DO NOT DISTRIBUTE UNSECURED</p>
            <p style={{ margin: '0.25rem 0 0 0' }}>Powered by digital_public_safety_platform.py (Notebook 8, Rev 4) | 6 Specialized AI Engines</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportViewer;
